package View;

import Controller.SalaController;
import Model.Sala;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alexandre
 */
public class frmSalas extends javax.swing.JFrame {

    public static Sala salaEstatica;

    /**
     * Creates new form frmSalas
     */
    public frmSalas() {
        initComponents();
    }

    /*Opção usada para exibir ou ocultar os botões: 1 para adicionar e 0 para editar*/
    public frmSalas(int opc) {
        initComponents();
        if (opc == 1) {
            btnSalasEditar.setVisible(false);
        } else {
            btnSalasAdd.setVisible(false);            
            txtSalaNro.setText(String.valueOf(salaEstatica.getNumero()));
            txtSalasAndar.setText(String.valueOf(salaEstatica.getAndar()));
            txtSalasBloco.setText(String.valueOf(salaEstatica.getBloco()));
            txtSalasProprietario.setText(String.valueOf(salaEstatica.getProprietario()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSalaNro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSalasBloco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSalasAndar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSalasProprietario = new javax.swing.JTextField();
        btnSalasAdd = new javax.swing.JButton();
        btnSalasEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULÁRIO DE SALA");

        jLabel1.setText("Número .:");

        jLabel2.setText("Bloco .:");

        jLabel3.setText("Andar .:");

        jLabel4.setText("Proprietário .:");

        btnSalasAdd.setText("ADICIONAR");
        btnSalasAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalasAddActionPerformed(evt);
            }
        });

        btnSalasEditar.setText("EDITAR");
        btnSalasEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalasEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSalaNro, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(txtSalasAndar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalasBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalasProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalasAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(btnSalasEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSalaNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtSalasBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSalasAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtSalasProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalasAdd)
                    .addComponent(btnSalasEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalasAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalasAddActionPerformed
        SalaController sc = new SalaController();
        Sala s = new Sala();
        s.setAndar(Integer.parseInt(txtSalasAndar.getText().trim()));
        s.setBloco(Integer.parseInt(txtSalasBloco.getText().trim()));
        s.setNumero(Integer.parseInt(txtSalaNro.getText().trim()));
        s.setProprietario(Integer.parseInt(txtSalasProprietario.getText().trim()));

        if (sc.cadastrar(s)) {
            JOptionPane.showMessageDialog(null, "Sala Adicionada com sucesso !", "SUCESSO !", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else
            JOptionPane.showMessageDialog(null, "Erro ao Adicionar", "ERRO !", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnSalasAddActionPerformed

    private void btnSalasEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalasEditarActionPerformed
        SalaController sc = new SalaController();
        Sala s = new Sala();
        s.setId(salaEstatica.getId());
        s.setAndar(Integer.parseInt(txtSalasAndar.getText()));
        s.setBloco(Integer.parseInt(txtSalasBloco.getText()));
        s.setNumero(Integer.parseInt(txtSalaNro.getText()));
        s.setProprietario(Integer.parseInt(txtSalasProprietario.getText()));
        if (sc.atualizar(s))
            JOptionPane.showMessageDialog(null, "Sala Editada com sucesso !", "SUCESSO !", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "Erro na Edição!", "ERRO !", JOptionPane.ERROR_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnSalasEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSalas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalasAdd;
    private javax.swing.JButton btnSalasEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtSalaNro;
    private javax.swing.JTextField txtSalasAndar;
    private javax.swing.JTextField txtSalasBloco;
    private javax.swing.JTextField txtSalasProprietario;
    // End of variables declaration//GEN-END:variables

    private void limpar_telas() {
        txtSalaNro.setText("");
        txtSalasAndar.setText("");
        txtSalasBloco.setText("");
        txtSalasProprietario.setText("");
    }
}
